name: Nix Flake Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    if: ${{ !github.event.pull_request.head.repo.fork }} # not for forks
    strategy:
      matrix:
        platform: [linux, macos]
    runs-on: [self-hosted, "${{ matrix.platform }}"]
    steps:
      - uses: actions/checkout@v7
      - run: nix flake check
