name: Update Nix Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # 12:00 UTC+8

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - run: nix run .#update-inputs
      - uses: actions/upload-artifact@v7
        with:
          name: flake-lock
          path: flake.lock

  check:
    needs: update
    strategy:
      matrix:
        platform: [linux, macos]
    runs-on: [self-hosted, "${{ matrix.platform }}"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: flake-lock
      - run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached

  commit:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: flake-lock
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update inputs"
          file_pattern: flake.lock
