name: Update Nix Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # 12:00 UTC+8

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: false
      - run: nix run .#update-inputs
      - uses: peter-evans/create-pull-request@v8
        with:
          branch: update-inputs
          delete-branch: true
          title: "flake: update inputs"
          commit-message: "flake: update inputs"
          add-paths: flake.lock
